# Generated by Django 3.1.7 on 2021-03-29 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postuuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70)),
                ('username', models.CharField(max_length=70)),
                ('published_on', models.DateTimeField(auto_now=True)),
                ('contenet', models.JSONField()),
            ],
        ),
    ]
